sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t oldschoolweaver/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true oldschoolweaver/docker-react npm run test